### PR TITLE
My Nightly Update

### PR DESCRIPTION
**Pull request by ghost**
Remember that obscure quest rule Weapon Animation Fix we never got around to fully implementing. With this it actually does something! Also Diagonal Constant traps should be a thing, with angelscript simplification. I went ahead and did that.

### CODE REVIEW

**Comment by Saffith** [comment]
Right now, the goal is not to break things. It's really not the time for new features.

**Comment by Tamamo89** [comment]
Says the person who broke shops. :p

**Comment by ghost** [comment]
Indeed, This is what happens when you release something too early. The code is such a mess right now, I wouldn't even commit any new features to this. Gleeok is right, this had to be done. Otherwise we would still be talking about it a year from now. As for fixing the spin attack. I'm going to be looking into that today.

**Comment by Gleeok** [comment]
Make sure you compile and run any scripts first to make sure they actually compile!

**Pull request closed without merging**
