### PR TITLE
Updated ffc swap (#4)

### PR DESCRIPTION
**Pull request by ghost**
- Updated ffc swap
- Updated zdefs.h
- Updated makefile
- Updated questRules.cpp

ffSWAPNEXT was bugged. I'm confident I fixed it. Also added a compatibility rule so the flag only effects speed. I haven't implemented the compatibility section into qst.cpp yet though.

### CODE REVIEW

**Comment by Saffith** [comment]
There doesn't appear to be an issue in 2.50.x. There's no need for a compatibility rule if the problem doesn't exist in any released version.

**Comment by ghost** [comment]
```
if((prvscr.ffflags[j]&ffSWAPNEXT)||(prvscr.ffflags[j]&ffSWAPPREV))
{
    int k=0;

    if(prvscr.ffflags[j]&ffSWAPNEXT)
    k=j<31?j+1:0;

    if(prvscr.ffflags[j]&ffSWAPPREV)
    k=j>0?j-1:31;

    zc_swap(prvscr.ffxdelta[j],prvscr.ffxdelta[k]);
    zc_swap(prvscr.ffydelta[j],prvscr.ffydelta[k]);
    zc_swap(prvscr.ffxdelta2[j],prvscr.ffxdelta2[k]);
    zc_swap(prvscr.ffydelta2[j],prvscr.ffydelta2[k]);
    zc_swap(prvscr.fflink[j],prvscr.fflink[k]);
    zc_swap(prvscr.ffwidth[j],prvscr.ffwidth[k]);
    zc_swap(prvscr.ffheight[j],prvscr.ffheight[k]);
    zc_swap(prvscr.ffflags[j],prvscr.ffflags[k]);
}
```

The above code from the 2.5.x branch says elsewise. It causes the same thing to happen actually it swaps everything when the tooltip says it should only swap speed.

**Comment by Saffith** [comment]
It's the description that's wrong, not the behavior. In any case, it would make more sense to add a "swap speed only" checkbox rather than a quest rule.

**Comment by ghost** [comment]
I would prefer that as well. I'll work on that today.

**Comment by evouga** [comment]
Closing as there is nothing to do.

Feel free to send a new request with the "swap speed only" checkbox (if there's *really* a need for this?)

**Pull request closed without merging**
