### PR TITLE
Fixed sideview vires and f6 mouse.

### PR DESCRIPTION
**Pull request by arceusplayer11**
Fixed Vires not working in sideview.

Fixed mouse not disappearing on f6.

### CODE REVIEW

**Review by ZoriaRPG — COMMENTED** [review]
if (tempguy.misc9!=e9tPOLSVOICE&&tempguy.misc9!=e9tVIRE) tempguy.moveflags = FLAG_OBEYS_GRAV | FLAG_CAN_PITFALL;

Did vires fall in 2.50.x? if not, then this is wrong.

**Review by ZoriaRPG — COMMENTED** [review]
eat_buttons()

You are commenting out eating the map button. This on the surface appears likely to cause issues.

**Comment by arceusplayer11** [comment]
Vires did not fall in 2.50; but I figured the reason they broke was Rob trying to allow them to fall in sideview. I kept his behavior (broken as it is), but it now requires the moveflag being checked, and it defaults to unchecked for vires in older quests.

Also, that was my error. I was attempting to fix inputs not working on the pause screen; it's a weird issue because it eats every keyboard input, such as enter and f6, while greyed out/paused, but not while the game is active, which leads me to believe it's an issue somewhere in the code. I was unable to resolve the error, but I haven't exactly gotten the hang of branching fixes and etc yet. Fixed now.

Also, that is not the map button; I was confused too! Map button is referred to as "P" instead of "M"; "M" is menu (which is defaulted to the escape key).

**Review by ZoriaRPG — COMMENTED** [review]
I am not sold that vires should have the change as inserted, but I would approve this. The issue is that I am unsure if approving this would also pull any of your other changes in the npc-?>Data PR, and if they did, I cannot approve it, as that is hellishly broken.

**Comment by arceusplayer11** [comment]
This is a separate branch.

**Pull request merged**
