### PR TITLE
Fix for #117

### PR DESCRIPTION
**Pull request by ntfwc**
This allows ZC to build without issue on Linux.

### CODE REVIEW

**Comment by evouga** [comment]
Isn't this file generated by Allegro's configure scripts? If so maybe it's better to invoke Allegro rather than add a specific instance of the file? (I thought I had set something like that up for Linux compilation but it could be broken...)

**Comment by gwx** [comment]
I cloned a clean repo to try building, and I didn't encounter any error. Trying with the fix seems to work fine as well, so I'm not quite sure what's going on here.

**Comment by ntfwc** [comment]
For me, if I build clean without this change, I get
`
fatal error: allegro/platform/alunixac.h: No such file or directory
`
So I don't know, maybe there is another instance of it somewhere in your include paths?

**Comment by evouga** [comment]
Here is the part that should invoke that Allegro config script: (CMakeLists.txt line 150)

`execute_process(COMMAND "${CMAKE_COMMAND}" "-H${CMAKE_SOURCE_DIR}/allegro" "-B${CMAKE_SOURCE_DIR}/allegro" WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/allegro")`

This should invoke allegro/CMakeLists.txt, and in particular run the following bit at the end

````
if(UNIX)
    configure_file(
        ${CMAKE_SOURCE_DIR}/include/allegro/platform/alunixac.h.cmake
        ${CMAKE_SOURCE_DIR}/extra/alunixac.h
        )
endif(UNIX)
````

which should generate the include file.

Is there anything in your CMake output that could tell us which part of the above isn't working correctly on your machine?

**Comment by evouga** [comment]
Actually I think I see the issue. Can you try the latest commit?

**Comment by ntfwc** [comment]
The latest commit builds fine

**Pull request closed without merging**
